openapi: 3.0.1
info:
  title: Hello World Plugin
  description: Plugin for saying Hello to our end-users.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /hello/{name}:
    get:
      operationId: getHelloWorld
      summary: Get a response to say hello world to the end user.
      parameters:
      - in: path
        name: name
        schema:
            type: string
        required: true
        description: The name of the user.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getHelloWorldResponse'

components:
  schemas:
    getHelloWorldResponse:
      type: object
      properties:
        hello:
          type: string
          description: The hello world message to the end user.
